import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { FormEvent, useCallback, useEffect, useRef } from 'react';
import styles from '../styles/Home.module.css'
import Input from './components/Input'
import Modal, { ModalProps } from './modal/index'

const Home: NextPage = () => {
  const ref = useRef<HTMLInputElement>(null);
  const modalRef = useRef<ModalProps>(null);

  const handleModal = useCallback(() => {
    modalRef.current?.handleModal()
  }, []);

  const handleSubmit = useCallback((e: FormEvent) => {
    e.preventDefault();

    if (ref.current?.value) {
      ref.current.style.background="#111"
      ref.current.style.width="40rem"
      ref.current.style.color="#fff"
      ref.current.style.fontSize="2rem"
    }
    ref.current?.focus();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ position: "relative" }}>
        <form onSubmit={handleSubmit}>
          <Input ref={ref} placeholder="escreva" />
          <button type="submit" style={{ padding: "1rem" }}>
            Focus
          </button>
          <button
            type="submit"
            onClick={handleModal}
            style={{ padding: "1rem" }}
          >
            Open Modal
          </button>
        </form>
        <Modal ref={modalRef} />
      </main>
    </div>
  );
}

export default Home
